// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Assert() {
  return window['go']['SSHCommand']['SSHClass']['Assert']();
}

export function CancelAutoLogin() {
  return window['go']['SSHCommand']['SSHClass']['CancelAutoLogin']();
}

export function Close() {
  return window['go']['SSHCommand']['SSHClass']['Close']();
}

export function HelpSetInfo() {
  return window['go']['SSHCommand']['SSHClass']['HelpSetInfo']();
}

export function NewSession() {
  return window['go']['SSHCommand']['SSHClass']['NewSession']();
}

export function RunAutoLogin() {
  return window['go']['SSHCommand']['SSHClass']['RunAutoLogin']();
}

export function RunCommand(arg1) {
  return window['go']['SSHCommand']['SSHClass']['RunCommand'](arg1);
}

export function RunSetAcInfo(arg1, arg2) {
  return window['go']['SSHCommand']['SSHClass']['RunSetAcInfo'](arg1, arg2);
}

export function RunSetScutInfo(arg1, arg2) {
  return window['go']['SSHCommand']['SSHClass']['RunSetScutInfo'](arg1, arg2);
}

export function RunSyncTime() {
  return window['go']['SSHCommand']['SSHClass']['RunSyncTime']();
}

export function RunWiredLogin() {
  return window['go']['SSHCommand']['SSHClass']['RunWiredLogin']();
}

export function RunWirelessLogin() {
  return window['go']['SSHCommand']['SSHClass']['RunWirelessLogin']();
}

export function SetOut(arg1) {
  return window['go']['SSHCommand']['SSHClass']['SetOut'](arg1);
}
