// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {io} from '../models';

export function Assert():Promise<void>;

export function CancelAutoLogin():Promise<void>;

export function Close():Promise<void>;

export function HelpSetInfo():Promise<void>;

export function NewSession():Promise<void>;

export function RunAutoLogin():Promise<void>;

export function RunCommand(arg1:string):Promise<void>;

export function RunSetAcInfo(arg1:string,arg2:string):Promise<void>;

export function RunSetScutInfo(arg1:string,arg2:string):Promise<void>;

export function RunSyncTime():Promise<void>;

export function RunWiredLogin():Promise<void>;

export function RunWirelessLogin():Promise<void>;

export function SetOut(arg1:io.Writer):Promise<void>;
